security:
    encoders:
        Symfony\Component\Security\Core\User\UserInterface:
            algorithm: bcrypt
    providers:
        app_user_provider:
            id: App\Module\Authentication\Security\UserProvider
    firewalls:
        login:
            pattern: ^/login
            stateless: true
            anonymous: true
            json_login:
                check_path: /login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        main:
            anonymous: true
            stateless: true
            lazy: true
            provider: app_user_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
    access_control:
        - { path: ^/login,    roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/,         roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/,         roles: IS_AUTHENTICATED_ANONYMOUSLY }